### ISSUE TITLE
Build with a static CRT so that users don't need Visual Studio files

### ISSUE THREAD

**Issue by Lokathor** [iceiix/stevenarella#318] opened 2020-05-27 21:26 UTC
Add the following to `.cargo/config` within the project:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i586-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```
And then users will not need the visual studio redistributable files to run the program.

This *slightly* increases binary size (depending on how much of the Windows CRT you use), but it's a good trade.

**Comment by iceiix** [comment] 2020-06-20 23:37
Looks like this should be an easy change and it appears to be a worthwhile compatibility/size tradeoff. Waiting on AppVeyor CI to finish to merge and test…

**Comment by iceiix** [comment] 2020-06-21 18:52
Testing adding .cargo/config as above and rebuilding locally on Windows 10, with rustc 1.44.1, I'm seeing steven.exe is the same size before and after the change:

 11,908,608 steven.exe

not sure why the change doesn't appear to be picked up, any idea what I'm missing?

Documentation on the crt-static feature: https://github.com/alexcrichton/rfcs/blob/crt-link/text/0000-crt-static.md

**Comment by iceiix** [comment] 2020-06-28 02:01
note: if can find out how to enable this change in cargo, can remove the from readme:

> The Visual Studio 2017 Redistributable is required to run these builds.

**Comment by iceiix** [comment] 2020-07-01 00:57
https://github.com/iceiix/stevenarella/commit/6b13fa3aabb6a9d1f83e426c821aa4d531031eb0 adds GitHub actions, which now enable +crt-static. To do:

- [ ] Move to .cargo/config checked into the project
- [ ] Confirm the change with and without the flag, retest without the Visual Studio files installed
- [ ] Update readme to remove "The Visual Studio 2017 Redistributable is required to run these builds" after confirmed

**Comment by iceiix** [comment] 2020-07-05 18:19
before:

```
07/05/2020  10:00 AM             5,620 libstevenarella.d
07/05/2020  09:59 AM        16,630,494 libstevenarella.rlib
10/30/2018  03:40 PM    <DIR>          native
11/30/2018  12:37 PM             4,103 steven.d
11/30/2018  12:37 PM        11,908,608 steven.exe
11/30/2018  12:37 PM         4,034,560 steven.pdb
07/05/2020  10:29 AM             5,616 stevenarella.d
07/05/2020  09:59 AM            10,240 stevenarella.dll
07/05/2020  10:00 AM             5,620 stevenarella.dll.d
07/05/2020  09:59 AM             1,896 stevenarella.dll.lib
07/05/2020  10:00 AM        13,936,128 stevenarella.exe
07/05/2020  10:00 AM         4,149,248 stevenarella.pdb
```

after:

```
07/05/2020  10:00 AM             5,620 libstevenarella.d
07/05/2020  11:07 AM        16,630,500 libstevenarella.rlib
10/30/2018  03:40 PM    <DIR>          native
11/30/2018  12:37 PM             4,103 steven.d
11/30/2018  12:37 PM        11,908,608 steven.exe
11/30/2018  12:37 PM         4,034,560 steven.pdb
07/05/2020  11:08 AM             5,616 stevenarella.d
07/05/2020  11:07 AM           132,096 stevenarella.dll
07/05/2020  10:00 AM             5,620 stevenarella.dll.d
07/05/2020  09:59 AM             1,896 stevenarella.dll.lib
07/05/2020  11:08 AM        14,072,320 stevenarella.exe
07/05/2020  11:08 AM         8,392,704 stevenarella.pdb
```

while the .exe size didn't change, the .dll increased from 10K to 129K

**Closed** 2020-07-05 18:20 UTC
Labels: enhancement
