### ISSUE TITLE
Handling death

### ISSUE THREAD

**Issue by terrarier2111** [iceiix/stevenarella#569] opened 2021-07-04 14:21 UTC
Currently there is the issue that if you die you can't do anything to respawn, meaning that if the server doesn't respawn you in some way, you won't respawn ever, rendering the server you died on unplayable.

**Comment by iceiix** [comment] 2021-07-18 16:31
Duplicate of https://github.com/iceiix/stevenarella/issues/61 Death, but I agree this is important (necessary for survival mode).

**Closed by iceiix** 2021-07-18 16:31 UTC
Labels: duplicate
