### ISSUE TITLE
15w39c : Thread panic on Result::unwrap() Err value SendError(..)

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#364] opened 2020-07-05 00:17 UTC
Connected to vanilla 15w39c server

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src\main.rs:122:13
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
  12: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\option.rs:1268
  13: core::result::Result<(), std::sync::mpsc::SendError<core::result::Result<stevenarella::server::Server, steven_protocol::protocol::Error>>>::unwrap<(),std::sync::mpsc::SendError<core::result::Result<stevenarella::server::Server, steven_protocol::protocol::
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libcore\result.rs:1005
  14: stevenarella::{{impl}}::connect_to::{{closure}}
             at D:\Github\stevenarella\src\main.rs:122

**Comment by iceiix** [comment] 2020-07-05 02:06
This suggests a connectivity issue to the server, the failing line is:

```rust
        thread::spawn(move || {
            tx.send(server::Server::connect(
                resources,
                profile,
                &address,
                protocol_version,
                forge_mods,
            ))
```

Are there steps where you can reproduce this issue reliably? I suspect it is triggered by another problem, for example if the client dies, this is not yet handled (#61 death), or if there is another event which causes the server to reject the client.

Also worth noting, while the 15w39c snapshot protocol is supported, it is generally easier to test and diagnose issues in the release versions, since there are often multiple server implementations or variations to help narrow down bugs (and there are many bugs in this project, no doubt, not necessarily specific to this version…)

**Comment by skillman623** [comment] 2020-07-05 02:14
No, I cannot reliably reproduce this issue. I will post back with more details if I can get this (as well as other bugs) to happen in other versions.

**Comment by iceiix** [comment] 2020-12-28 19:59
Closing since this wasn't reproducible, also I think it was a server connectivity issue, but if you can reliably repro please reopen

**Closed by iceiix** 2020-12-28 19:59 UTC
Labels: bug, wontfix
